#!/bin/bash

# Change working directory to the directory where the script is located
cd "$(dirname "$0")"

# Activate the virtual environment
source "./.venv/bin/activate"

# Build the executable
pyinstaller --onefile camera-record.py

# move the executable to the root directory
mv ./dist/camera-record ./camera-record

# Delete the garbage files generated by pyinstaller
rm -rf ./build
rm -rf ./dist
rm -rf ./camera-record.spec